### ISSUE TITLE
Questions about cppcon 2016 presentation

### ISSUE THREAD

**Issue by cyberkm** [lefticus/presentations#3]
Another question about presentations:

```
#include <string>

struct S {
  S(std::string t_s) : s(std::move(t_s)) {}
  std::string s;
};

int main()
{
  for (int i = 0; i < 10000000; ++i) {
    S o(std::string("a not very short string") + "b");
  }
}
```

What do you think about preallocating enough space on the string ahead and just fill it with "b" chars?
In this case you already know how many chars you need to append, so we can use it to save reallocations.

**Comment by lefticus** [comment]
That's actually only appending exactly 1 "b" the `for` loop is so that it takes enough time to measure. The point was to not use temporary values if you don't need to, since there is some cost there in managing the lifetime of the temporary (which was on the previous slide).
